version: "3.5"

volumes:
  teste-mysql-data:
    driver: local

services:
  mysql:
    image: mysql:5.7
    container_name: teste_mysql
    environment:
      - MYSQL_DATABASE=teste
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=secret
    volumes:
      - teste-mysql-data:/var/lib/mysql:delegated
    ports:
      - "3306:3306"